name: gestiondossier
description: A new Flutter project.

version: 1.0.0+1

environment:  
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+3
  path_provider: ^2.0.15
  get: ^4.6.5
  google_fonts: ^4.0.4
  file_picker: ^3.0.4
  flutter_file_dialog: ^3.0.2
  path: ^1.8.0

  # file_saver: ^0.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
